name: ellipsometry
channels:
  - conda-forge
dependencies:
  # Pin to a Binder-friendly Python
  - python=3.11

  # Jupyter stack
  - jupyterlab
  - ipykernel
  - ipywidgets

  # Scientific Python
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - openpyxl
  - sympy

  # System libs that are safe cross-platform 
  - zeromq
  - pyzmq

  # enable pip installs for packages that are PyPI-only
  - pip
  - pip:
      - tmm-fast==0.2.1
      - gymnasium==1.2.0
      - torch==2.4.*            # (CPU wheels from PyPI)
      # or: - torch==2.4.*+cpu    # (older naming; only if needed)

